export const SORTING_CONSTANTS = {
  DEFAULT_BAR_GAP: 5,
  DEFAULT_BAR_WIDTH: 25,
  DEFAULT_DELAY: 50,
  DEFAULT_SPEED: 200,
  MAX_BAR_GAP: 10,
  MAX_BAR_WIDTH: 100,
  MAX_DELAY: 1000,
  MAX_SPEED: 1000,
  MIN_BAR_GAP: 0,
  MIN_BAR_WIDTH: 10,
  MIN_DELAY: 0,
  MIN_SPEED: 0,
};
